name: am-hexacopter-rl
channels:
  - defaults
dependencies:
  - pip=25.0
  - python=3.11.11

  - pip:
      - nbformat
      - sympy
      - pytest
      - plotly
      - jinja2
      - pydantic
      - pynput
      - tensorboard
      - pybind11-stubgen  
      - playground
      - ipykernel
      - matplotlib
      - pyqtgraph
      - PyQt6
      - jax[cuda12]==0.6.0
      - pytest
      - -e . # This is to install the repo itself. TODO: This might not be great.
      - git+https://github.com/AndruGomes13/brax.git@ppo_curriculum
