[project]
name = "am_hexacopter_rl"
version = "0.1.0"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.ruff]
extend-select = ["C4", "NPY", "PD", "SIM", "TCH"]
ignore = ["E501"]
show-fixes = true
# target-version = "py310"

# change the default line length number or characters.
line-length = 150